const actionTypes = {
  FETCH_MOVIES: "FETCH_MOVIES",
  FETCH_GENRES: "FETCH_GENRES",
  FETCH_SORT_BY_LIST: "FETCH_SORT_BY_LIST",
  SELECT_MOVIE: "SELECT_MOVIE",
  SELECT_SEARCH: "SELECT_SEARCH",
  SELECT_SORTED_BY: "SELECT_SORTED_BY",
  DELETE_MOVIE: "DELETE_MOVIE",
};

export default actionTypes;
